# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routes.proto

require 'google/protobuf/empty_pb'
require 'google/api/annotations_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("routes.proto", :syntax => :proto3) do
    add_message "wwapi.v1.ContainerBuildParameter" do
      repeated :containerNames, :string, 1
      optional :force, :bool, 2
      optional :all, :bool, 3
      optional :default, :bool, 4
    end
    add_message "wwapi.v1.ContainerDeleteParameter" do
      repeated :containerNames, :string, 1
    end
    add_message "wwapi.v1.ContainerImportParameter" do
      optional :source, :string, 1
      optional :name, :string, 2
      optional :force, :bool, 3
      optional :update, :bool, 4
      optional :build, :bool, 5
      optional :default, :bool, 6
    end
    add_message "wwapi.v1.ContainerInfo" do
      optional :name, :string, 1
      optional :nodeCount, :uint32, 2
      optional :kernelVersion, :string, 3
    end
    add_message "wwapi.v1.ContainerListResponse" do
      repeated :containers, :message, 1, "wwapi.v1.ContainerInfo"
    end
    add_message "wwapi.v1.ContainerShowParameter" do
      optional :containerName, :string, 1
    end
    add_message "wwapi.v1.ContainerShowResponse" do
      optional :Name, :string, 1
      optional :Rootfs, :string, 2
      repeated :Nodes, :string, 3
    end
    add_message "wwapi.v1.NodeNames" do
      repeated :nodeNames, :string, 1
    end
    add_message "wwapi.v1.NodeField" do
      optional :source, :string, 1
      optional :value, :string, 2
      optional :print, :string, 3
    end
    add_message "wwapi.v1.NetDev" do
      optional :device, :message, 1, "wwapi.v1.NodeField"
      optional :hwaddr, :message, 2, "wwapi.v1.NodeField"
      optional :ipaddr, :message, 3, "wwapi.v1.NodeField"
      optional :netmask, :message, 4, "wwapi.v1.NodeField"
      optional :gateway, :message, 5, "wwapi.v1.NodeField"
      optional :type, :message, 6, "wwapi.v1.NodeField"
      optional :onboot, :message, 7, "wwapi.v1.NodeField"
      optional :default, :message, 8, "wwapi.v1.NodeField"
    end
    add_message "wwapi.v1.NodeInfo" do
      optional :id, :message, 1, "wwapi.v1.NodeField"
      optional :comment, :message, 2, "wwapi.v1.NodeField"
      optional :cluster, :message, 3, "wwapi.v1.NodeField"
      optional :discoverable, :message, 4, "wwapi.v1.NodeField"
      optional :container, :message, 5, "wwapi.v1.NodeField"
      optional :kernelOverride, :message, 6, "wwapi.v1.NodeField"
      optional :kernelArgs, :message, 7, "wwapi.v1.NodeField"
      optional :systemOverlay, :message, 8, "wwapi.v1.NodeField"
      optional :runtimeOverlay, :message, 9, "wwapi.v1.NodeField"
      optional :ipxe, :message, 10, "wwapi.v1.NodeField"
      optional :init, :message, 11, "wwapi.v1.NodeField"
      optional :root, :message, 12, "wwapi.v1.NodeField"
      optional :assetKey, :message, 13, "wwapi.v1.NodeField"
      optional :ipmiIpaddr, :message, 14, "wwapi.v1.NodeField"
      optional :ipmiNetmask, :message, 15, "wwapi.v1.NodeField"
      optional :ipmiPort, :message, 16, "wwapi.v1.NodeField"
      optional :ipmiGateway, :message, 17, "wwapi.v1.NodeField"
      optional :ipmiUserName, :message, 18, "wwapi.v1.NodeField"
      optional :ipmiInterface, :message, 19, "wwapi.v1.NodeField"
      optional :ipmiPassword, :message, 20, "wwapi.v1.NodeField"
      repeated :profiles, :string, 21
      repeated :groupProfiles, :string, 22
      map :NetDevs, :string, :message, 23, "wwapi.v1.NetDev"
      map :Tags, :string, :message, 24, "wwapi.v1.NodeField"
      map :Keys, :string, :message, 25, "wwapi.v1.NodeField"
    end
    add_message "wwapi.v1.NodeListResponse" do
      repeated :nodes, :message, 1, "wwapi.v1.NodeInfo"
    end
    add_message "wwapi.v1.NodeAddParameter" do
      optional :cluster, :string, 1
      optional :discoverable, :bool, 2
      optional :gateway, :string, 3
      optional :hwaddr, :string, 4
      optional :ipaddr, :string, 5
      optional :netdev, :string, 6
      optional :netmask, :string, 7
      optional :netname, :string, 8
      optional :type, :string, 9
      repeated :nodeNames, :string, 10
    end
    add_message "wwapi.v1.NodeDeleteParameter" do
      optional :force, :bool, 1
      repeated :nodeNames, :string, 2
    end
    add_message "wwapi.v1.NodeSetParameter" do
      optional :comment, :string, 1
      optional :container, :string, 2
      optional :kernelOverride, :string, 3
      optional :kernelArgs, :string, 4
      optional :netname, :string, 5
      optional :netdev, :string, 6
      optional :ipaddr, :string, 7
      optional :netmask, :string, 8
      optional :gateway, :string, 9
      optional :hwaddr, :string, 10
      optional :type, :string, 11
      optional :onboot, :string, 12
      optional :netDefault, :string, 13
      optional :netdevDelete, :bool, 14
      optional :cluster, :string, 15
      optional :ipxe, :string, 16
      optional :initOverlay, :string, 17
      optional :runtimeOverlay, :string, 18
      optional :systemOverlay, :string, 19
      optional :ipmiIpaddr, :string, 20
      optional :ipmiNetmask, :string, 21
      optional :ipmiPort, :string, 22
      optional :ipmiGateway, :string, 23
      optional :ipmiUsername, :string, 24
      optional :ipmiPassword, :string, 25
      optional :ipmiInterface, :string, 26
      optional :allNodes, :bool, 27
      optional :profile, :string, 28
      repeated :profileAdd, :string, 29
      repeated :profileDelete, :string, 30
      optional :force, :bool, 31
      optional :init, :string, 32
      optional :discoverable, :bool, 33
      optional :undiscoverable, :bool, 34
      optional :root, :string, 35
      repeated :tags, :string, 36
      repeated :tagsDelete, :string, 37
      optional :assetKey, :string, 38
      repeated :nodeNames, :string, 39
      optional :ipmiWrite, :string, 40
    end
    add_message "wwapi.v1.NodeStatus" do
      optional :nodeName, :string, 1
      optional :stage, :string, 2
      optional :sent, :string, 3
      optional :ipaddr, :string, 4
      optional :lastseen, :int64, 5
    end
    add_message "wwapi.v1.NodeStatusResponse" do
      repeated :nodeStatus, :message, 1, "wwapi.v1.NodeStatus"
    end
    add_message "wwapi.v1.VersionResponse" do
      optional :apiPrefix, :string, 1
      optional :apiVersion, :string, 2
      optional :warewulfVersion, :string, 3
    end
  end
end

module Wwapi
  module V1
    ContainerBuildParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.ContainerBuildParameter").msgclass
    ContainerDeleteParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.ContainerDeleteParameter").msgclass
    ContainerImportParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.ContainerImportParameter").msgclass
    ContainerInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.ContainerInfo").msgclass
    ContainerListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.ContainerListResponse").msgclass
    ContainerShowParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.ContainerShowParameter").msgclass
    ContainerShowResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.ContainerShowResponse").msgclass
    NodeNames = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.NodeNames").msgclass
    NodeField = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.NodeField").msgclass
    NetDev = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.NetDev").msgclass
    NodeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.NodeInfo").msgclass
    NodeListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.NodeListResponse").msgclass
    NodeAddParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.NodeAddParameter").msgclass
    NodeDeleteParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.NodeDeleteParameter").msgclass
    NodeSetParameter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.NodeSetParameter").msgclass
    NodeStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.NodeStatus").msgclass
    NodeStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.NodeStatusResponse").msgclass
    VersionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("wwapi.v1.VersionResponse").msgclass
  end
end
